# Generated by Django 5.1.7 on 2025-03-13 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='bar_membership',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='certification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='education',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='slogan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='tagline',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('responsibilities', models.TextField()),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='core.lawyer')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
