# Generated by Django 5.1.7 on 2025-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lawyer_bar_membership_lawyer_certification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
