# Generated by Django 5.1.7 on 2025-03-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
