# Generated by Django 5.1.7 on 2025-03-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_experience_end_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='is_current',
        ),
    ]
